INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Ounce');
INSERT INTO unit_of_measure (description) VALUES ('dash');

INSERT INTO ingredient (description) VALUES ('avocado');
INSERT INTO ingredient (description) VALUES ('salt');
INSERT INTO ingredient (description) VALUES ('lime juice');
INSERT INTO ingredient (description) VALUES ('red onion');
INSERT INTO ingredient (description) VALUES ('chili');
INSERT INTO ingredient (description) VALUES ('cilantro');
INSERT INTO ingredient (description) VALUES ('black pepper');
INSERT INTO ingredient (description) VALUES ('tomato');
INSERT INTO ingredient (description) VALUES ('radish');
INSERT INTO ingredient (description) VALUES ('tortilla chips');